[package]
name = "pg-triple-store"
version = "0.2.1"
edition = "2024"

[dependencies]
diesel = { version = "2.3.12", features = ["postgres", "r2d2"] }
diesel_migrations = "2.3.2"
dotenvy = "0.15.7"
log = "0.4.33"
oxrdf = { version = "0.3.3", features = ["rdf-12"] }
oxrdfxml = { version = "0.2.4", features = ["rdf-12"] }
oxttl = { version = "0.2.3", features = ["rdf-12"] }
regex = "1.13.1"
spargebra = { version = "0.4.6", features = ["sparql-12"] }
uuid = { version = "1.26.0", features = ["v7"] }

[dev-dependencies]
env_logger = "0.11.10"
