[package]
name = "pg-triple-store"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.9", features = ["postgres", "r2d2"] }
diesel_migrations = "2.3.2"
dotenvy = "0.15.7"
log = "0.4.30"
oxrdf = { version = "0.3.3", features = ["rdf-12"] }
oxttl = { version = "0.2.3", features = ["rdf-12"] }
reqwest = { version = "0.13.4", features = ["blocking"] }
spargebra = { version = "0.4.6", features = ["sparql-12"] }
